POST http://localhost:8080/users
Content-Type: application/json

{
  "password": "hashed_password_1234",
  "sap_user_code": "SAP004"
}
###
GET http://localhost:8080/users
###
GET http://localhost:8080/users/19
###
PUT http://localhost:8080/users/21
Content-Type: application/json

{
  "password": "new_hashed_password",
  "sap_user_code": "SAP003"
}
###
DELETE http://localhost:8080/users/20
